/*
 * CommandPanel.java
 *
 * Created on Oct 25, 2011, 2:55:46 AM
 */
package com.dev;

import java.awt.Color;

public class CommandPanel extends javax.swing.JPanel {
    
	private static final long serialVersionUID = -7009105452723849595L;

	private Command cmd;

    public CommandPanel(final Command c) {
        initComponents();
        this.lblDesc.setText(c.getDescription());
        if(c.isSelected()){
            this.setSelected();
        }
        this.cmd=c;
        this.setToolTipText(c.toHtml());
    }

    public void setUnselected() {
        this.setBackground(Color.WHITE);
    }
    
    public void setSelected(){
        this.setBackground(Color.ORANGE);
    }
    
    public boolean isSelected(){
        return this.getBackground() == Color.ORANGE;
    }
    
    public void setSuccess() {
        this.lblExecuteInfo.setText(Utils.getNowTime());
        this.lblExecuteInfo.setForeground(Color.GREEN);
    }
    
    public boolean isSuccessful() {
        return this.getBackground() == Color.GREEN;
    }
    
    public void setFailure() {
        this.lblExecuteInfo.setText(Utils.getNowTime());
        this.lblExecuteInfo.setForeground(Color.RED);
    }
    
    public void clearStatus(){
        this.lblExecuteInfo.setText(Utils.EMPTY_STRING);
        this.lblExecuteInfo.setBackground(Color.WHITE);
    }

    
    public void switchSelection(){
        if (this.isSelected()) {
            this.setUnselected();
        } else {
            this.setSelected();
        }
    }
    
    public void updateStatus(){

        if(Command.SUCCESSFUL_STRING.equals(this.cmd.getStatus())){
            this.setSuccess();
        }else if(Command.FAILURE_STRING.equals(this.cmd.getStatus())){
            this.setFailure();
        }
        this.setUnselected();
        this.setRunComplete();
    }
    
    public Command getCommand(){
        return this.cmd;
    }
    
    public void setInprogress(){
        lblExecuteInfo.setIcon(new javax.swing.ImageIcon(ProjectManager.BASE_DIR + "pic/progress.gif"));
    }
    
    public void setRunComplete(){
        lblExecuteInfo.setIcon(null);
    }
    
    public void showMessageDialog(){
        if (!Utils.isEmptyString(cmd.getCmdResult())) {
            new MessageDialog(ProjectFrame.projectFrame, false, cmd.getCmdResult());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDesc = new javax.swing.JLabel();
        lblExecuteInfo = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(735, 51));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblDesc.setText("Description");

        lblExecuteInfo.setBackground(java.awt.Color.white);

        lblDetail.setForeground(new java.awt.Color(103, 218, 124));
        lblDetail.setText("Detial...");
        lblDetail.setToolTipText("");
        lblDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDetailMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblExecuteInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblDetail))
                .addContainerGap())
            .addComponent(lblExecuteInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getClickCount() == 1) {
            this.switchSelection();
        }
        if (evt.getClickCount() == 2) {
            this.switchSelection();
            this.showMessageDialog();
        }
    }//GEN-LAST:event_formMouseClicked

private void lblDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDetailMouseEntered
    this.showMessageDialog();
}//GEN-LAST:event_lblDetailMouseEntered

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblExecuteInfo;
    // End of variables declaration//GEN-END:variables
}
