/*
 * MessageDialog.java
 *
 * Created on Sep 21, 2011, 3:21:51 PM
 */
package com.dev;

import java.awt.datatransfer.Clipboard;
import javax.swing.JTextArea;

public class MessageDialog extends javax.swing.JDialog {

    
	private static final long serialVersionUID = 1L;
	/** Creates new form MessageDialog */
    public MessageDialog(java.awt.Frame parent, boolean modal, String msg) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pnMessage.setText(msg);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnMessage = new javax.swing.JTextPane();
        lblMaximize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblCopy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        pnMessage.setToolTipText("");
        pnMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMessageMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(pnMessage);

        lblMaximize.setBackground(new java.awt.Color(175, 205, 238));
        lblMaximize.setForeground(java.awt.Color.green);
        lblMaximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximize.setText("Maximize");
        lblMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaximizeMouseEntered(evt);
            }
        });

        lblClose.setForeground(new java.awt.Color(156, 113, 28));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("...Close...Dialog...");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });

        lblCopy.setForeground(new java.awt.Color(87, 92, 179));
        lblCopy.setText("Copy Selected");
        lblCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCopyMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(lblCopy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaximize)
                    .addComponent(lblClose)
                    .addComponent(lblCopy))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
       
    }//GEN-LAST:event_formFocusLost

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        
    }//GEN-LAST:event_formMouseExited

    private void pnMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMessageMouseExited
    }//GEN-LAST:event_pnMessageMouseExited

private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
    this.dispose();
}//GEN-LAST:event_lblCloseMouseEntered

private void lblMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeMouseEntered

}//GEN-LAST:event_lblMaximizeMouseEntered

private void lblCopyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCopyMouseEntered
    new JTextArea(this.pnMessage.getSelectedText()).copy();
}//GEN-LAST:event_lblCopyMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCopy;
    private javax.swing.JLabel lblMaximize;
    private javax.swing.JTextPane pnMessage;
    // End of variables declaration//GEN-END:variables
}
